# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import src.rpc.python.c2nl_pb2 as c2nl__pb2


class Code2NLStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.summarize = channel.unary_unary(
        '/Code2NL/summarize',
        request_serializer=c2nl__pb2.Code.SerializeToString,
        response_deserializer=c2nl__pb2.Summary.FromString,
        )


class Code2NLServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def summarize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Code2NLServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'summarize': grpc.unary_unary_rpc_method_handler(
          servicer.summarize,
          request_deserializer=c2nl__pb2.Code.FromString,
          response_serializer=c2nl__pb2.Summary.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Code2NL', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
