// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: c2nl.proto
#ifndef GRPC_c2nl_2eproto__INCLUDED
#define GRPC_c2nl_2eproto__INCLUDED

#include "c2nl.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class Code2NL final {
 public:
  static constexpr char const* service_full_name() {
    return "Code2NL";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status summarize(::grpc::ClientContext* context, const ::Code& request, ::Summary* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Summary>> Asyncsummarize(::grpc::ClientContext* context, const ::Code& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Summary>>(AsyncsummarizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Summary>> PrepareAsyncsummarize(::grpc::ClientContext* context, const ::Code& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Summary>>(PrepareAsyncsummarizeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void summarize(::grpc::ClientContext* context, const ::Code* request, ::Summary* response, std::function<void(::grpc::Status)>) = 0;
      virtual void summarize(::grpc::ClientContext* context, const ::Code* request, ::Summary* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Summary>* AsyncsummarizeRaw(::grpc::ClientContext* context, const ::Code& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Summary>* PrepareAsyncsummarizeRaw(::grpc::ClientContext* context, const ::Code& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status summarize(::grpc::ClientContext* context, const ::Code& request, ::Summary* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Summary>> Asyncsummarize(::grpc::ClientContext* context, const ::Code& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Summary>>(AsyncsummarizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Summary>> PrepareAsyncsummarize(::grpc::ClientContext* context, const ::Code& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Summary>>(PrepareAsyncsummarizeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void summarize(::grpc::ClientContext* context, const ::Code* request, ::Summary* response, std::function<void(::grpc::Status)>) override;
      void summarize(::grpc::ClientContext* context, const ::Code* request, ::Summary* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Summary>* AsyncsummarizeRaw(::grpc::ClientContext* context, const ::Code& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Summary>* PrepareAsyncsummarizeRaw(::grpc::ClientContext* context, const ::Code& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_summarize_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status summarize(::grpc::ServerContext* context, const ::Code* request, ::Summary* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_summarize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_summarize() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_summarize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status summarize(::grpc::ServerContext* /*context*/, const ::Code* /*request*/, ::Summary* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsummarize(::grpc::ServerContext* context, ::Code* request, ::grpc::ServerAsyncResponseWriter< ::Summary>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_summarize<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_summarize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_summarize() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Code, ::Summary>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Code* request, ::Summary* response) { return this->summarize(context, request, response); }));}
    void SetMessageAllocatorFor_summarize(
        ::grpc::MessageAllocator< ::Code, ::Summary>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Code, ::Summary>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_summarize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status summarize(::grpc::ServerContext* /*context*/, const ::Code* /*request*/, ::Summary* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* summarize(
      ::grpc::CallbackServerContext* /*context*/, const ::Code* /*request*/, ::Summary* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_summarize<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_summarize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_summarize() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_summarize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status summarize(::grpc::ServerContext* /*context*/, const ::Code* /*request*/, ::Summary* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_summarize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_summarize() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_summarize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status summarize(::grpc::ServerContext* /*context*/, const ::Code* /*request*/, ::Summary* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsummarize(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_summarize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_summarize() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->summarize(context, request, response); }));
    }
    ~WithRawCallbackMethod_summarize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status summarize(::grpc::ServerContext* /*context*/, const ::Code* /*request*/, ::Summary* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* summarize(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_summarize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_summarize() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Code, ::Summary>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Code, ::Summary>* streamer) {
                       return this->Streamedsummarize(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_summarize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status summarize(::grpc::ServerContext* /*context*/, const ::Code* /*request*/, ::Summary* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsummarize(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Code,::Summary>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_summarize<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_summarize<Service > StreamedService;
};


#endif  // GRPC_c2nl_2eproto__INCLUDED
